name: ahu_helper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  # 网络请求核心
  dio: ^5.3.0
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.0
  path_provider: ^2.1.2
  # 网页与Cookie提取
  webview_flutter: ^4.4.2
  flutter_inappwebview: ^6.0.0  # 使用最新的 6.0 版本
  
  # 辅助工具
  fluttertoast: ^8.2.4
  # 如果需要解析课表，还需要这个
  html: ^0.15.4 

  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
